roc_s0:
  sc:
    DigitalHalf:
      all:
        L1Offset: 10
        IdleFrame: 0xCCCCCCC
    GlobalAnalog:
      all:
        Delay87: 1
        Delay9: 2
    ReferenceVoltage:
      all:
        Vbg_1v: 4
        ExtCtest: 0
        IntCtest: 0
        Calib_dac: 0
      0:
        Inv_vref: 230
        Noinv_vref: 50
      1:
        Inv_vref: 240
        Noinv_vref: 50 
    Top:
      all:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        EN_LOCK_CONTROL: 0
        ERROR_LIMIT_SC: 0
    ch:
      all:
        LowRange: 0
roc_s1:
  sc:
    DigitalHalf:
      all:
        L1Offset: 10
        IdleFrame: 0xCCCCCCC
    GlobalAnalog:
      all:
        Delay87: 1
        Delay9: 2
    ReferenceVoltage:
      all:
        Vbg_1v: 4
        ExtCtest: 0
        IntCtest: 0
        Calib_dac: 0
      0:
        Inv_vref: 230
        Noinv_vref: 50
      1:
        Inv_vref: 240
        Noinv_vref: 50 
    Top:
      all:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        EN_LOCK_CONTROL: 0
        ERROR_LIMIT_SC: 0
    ch:
      all:
        LowRange: 0
roc_s2:
  sc:
    DigitalHalf:
      all:
        L1Offset: 10
        IdleFrame: 0xCCCCCCC
    GlobalAnalog:
      all:
        Delay87: 1
        Delay9: 2
    ReferenceVoltage:
      all:
        Vbg_1v: 4
        ExtCtest: 0
        IntCtest: 0
        Calib_dac: 0
      0:
        Inv_vref: 230
        Noinv_vref: 50
      1:
        Inv_vref: 240
        Noinv_vref: 50 
    Top:
      all:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        EN_LOCK_CONTROL: 0
        ERROR_LIMIT_SC: 0
    ch:
      all:
        LowRange: 0
