client:
  data_push_port: '8888'
  hw_type: TB
  outputDirectory: /home/hgcal/Desktop/software_test_Jia-Hao/hexactrl-sw/hexactrl-script_TB_23_08/data/TB3_D8_1/Threshold_tuning/pedestal_run/run_20230906_102738__trimmed_vrefinv_trimmed/
  run_type: pedestal_run
  serverIP: tbtester1
daq:
  IdelayStep: '8'
  NChips: '1'
  Number_of_events_per_readout: '-1'
  active_menu: randomL1A
  delayScanData_port: '8889'
  elinks_daq:
  - idcode: 0
    name: link0
    polarity: 1
  - idcode: 1
    name: link1
    polarity: 1
  elinks_trg:
  - idcode: 0
    name: link0
    polarity: 0
  - idcode: 1
    name: link1
    polarity: 1
  - idcode: 2
    name: link2
    polarity: 1
  - idcode: 3
    name: link3
    polarity: 0
  elinks_trg_phase:
  - idcode: 1
    name: link0
    polarity: 1
  menus:
    calibAndL1A:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
    calibAndL1AplusTPG:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
      trg_fifo_latency: 3
    delayScan:
      acquireLength: 1000
      delayStep: 1
      idlePattern: 0XACCCCCCC
      maxDelay: 512
    dummy:
      NEvents: 10000
      NEventsPerPush: 200
    externalL1A:
      NEvents: 10000
      bxCalibExt: 10
      lengthCalibExt: 2
      loopBack: true
      prescale: 0
      trg_fifo_latency: 3
      trgphase_fifo_latency: 15
    marsRndL1A:
      bx_min: 45
      log2_rand_bx_period: 10
    randomL1A:
      NEvents: 10000
      bx_min: 45
      log2_rand_bx_period: 0
    randomL1AplusTPG:
      NEvents: 10000
      bx_min: 45
      log2_rand_bx_period: 10
      trg_fifo_latency: 3
  zmqPushPull_port: '8888'
roc_s0:
  sc:
    DigitalHalf:
      0:
        Bx_offset: 2
        CalibrationSC: 1
        L1Offset: 10
      1:
        Bx_offset: 2
        CalibrationSC: 1
        L1Offset: 10
    GlobalAnalog:
      0:
        Cd: 0
        Cf: 10
        Cf_comp: 10
        Dacb_dynran: 3
        Dacb_vb_conv: 5
        Dacb_vbi_pa: 32  # please don't touch ever ever ever
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Gain_conv: 0
        Idac_inv: 6
        Idac_tot: 6
        ON_backup: 0
        ON_conv: 1
        Ref_pa_cm: 0
        Rf: 12
        SelExtADC: 0
        SelRisingEdge: 1
        En_hyst_tot: 0 #=====================disabling the hysteresis, 1 is enable, 0 is disable
      1:
        Cd: 0
        Cf: 10
        Cf_comp: 10
        Dacb_dynran: 3
        Dacb_vb_conv: 5
        Dacb_vbi_pa: 32   # please don't touch ever ever ever, it will crash if change
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Gain_conv: 0
        Idac_inv: 6
        Idac_tot: 6
        ON_backup: 0
        ON_conv: 1
        Ref_pa_cm: 0
        Rf: 12
        SelExtADC: 0
        SelRisingEdge: 1
        En_hyst_tot: 0 #=============================================disabling the hysteresis
    MasterTdc:
      0:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 10
        BIAS_I_FTDC_D: 10
        CTDC_CALIB_FREQUENCY: 2
        EN_MASTER_CTDC_VOUT_INIT: 0
        EN_MASTER_FTDC_VOUT_INIT: 0
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
        VD_CTDC_P_D: 16
        VD_CTDC_P_DAC_EN: 1
        VD_FTDC_P_D: 16
        VD_FTDC_P_DAC_EN: 1
      1:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 10
        BIAS_I_FTDC_D: 10
        CTDC_CALIB_FREQUENCY: 2
        EN_MASTER_CTDC_VOUT_INIT: 0
        EN_MASTER_FTDC_VOUT_INIT: 0
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
        VD_CTDC_P_D: 16
        VD_CTDC_P_DAC_EN: 1
        VD_FTDC_P_D: 16
        VD_FTDC_P_DAC_EN: 1
    ReferenceVoltage:
      0:
        Calib_2V5: 0
        Inv_vref: 700
        Noinv_vref: 850
        Refi: 1
        Toa_vref: 230 # was 240
        Tot_vref: 500 # was 630, 700
        Vbg_1v: 3
        choice_cinj: 0
        cmd_120p: 0
      1:
        Calib_2V5: 0
        Inv_vref: 667
        Noinv_vref: 850
        Refi: 1
        Toa_vref: 200
        Tot_vref: 500 # was 630, 800
        Vbg_1v: 3
        choice_cinj: 0
        cmd_120p: 0
    Top:
      0:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        RunL: 1
        RunR: 1
    calib:
      0:
        Gain_conv: 4
        Inputdac: 31
        dacb: 12
        sign_dac: 0
        trim_inv: 49
        trim_toa: 31
        trim_tot: 31
      1:
        Gain_conv: 4
        Inputdac: 31
        dacb: 12
        sign_dac: 0
        trim_inv: 27
        trim_toa: 31
        trim_tot: 31
    ch:
      0:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 57
        trim_toa: 46 # 58
        trim_tot: 30
      1:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 57
        trim_toa: 34 # 45
        trim_tot: 31
      2:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 52
        trim_toa: 39 # 52
        trim_tot: 31
      3:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 23
        trim_toa: 18 # 28
        trim_tot: 15
      4:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 7
        trim_toa: 46 # 55
        trim_tot: 31
      5:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 36
        trim_toa: 27 # 37
        trim_tot: 15
      6:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 27
        trim_toa: 21 # 31
        trim_tot: 11
      7:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 43
        trim_toa: 42 # 51
        trim_tot: 21
      8:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 46
        trim_toa: 25 # 30
        trim_tot: 51
      9:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 62
        trim_toa: 45 # 57
        trim_tot: 37
      10:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 7
        trim_toa: 13 # 22
        trim_tot: 1
      11:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 27
        trim_toa: 30 # 39
        trim_tot: 27
      12:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 36
        trim_toa: 26 # 35
        trim_tot: 12
      13:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 6
        trim_toa: 40 # 50
        trim_tot: 23
        Channel_off: 1
      14:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 53
        trim_toa: 33 # 46
        trim_tot: 26
      15:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 41
        trim_toa: 39 # 51
        trim_tot: 21
      16:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 31
        trim_toa: 46 # 57
        trim_tot: 42
      17:
        Gain_conv: 4
        HZ_noinv: 0
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 56
        trim_toa: 48 # 54
        trim_tot: 60
      18:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 62
        trim_toa: 26 # 32
        trim_tot: 60
      19:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 6
        trim_toa: 43 # 53
        trim_tot: 34
      20:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 52
        trim_toa: 35 # 46
        trim_tot: 35
      21:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 5
        trim_toa: 20 # 30
        trim_tot: 0
      22:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 50
        trim_toa: 38 # 47
        trim_tot: 30
      23:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 54
        trim_toa: 28 # 38
        trim_tot: 35
      24:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 55
        trim_toa: 39 # 46
        trim_tot: 29
      25:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 61
        trim_toa: 33 # 40
        trim_tot: 21
      26:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 53
        trim_toa: 46 # 53
        trim_tot: 35
      27:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 31
        trim_toa: 30 # 37
        trim_tot: 63
      28:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 0
        trim_toa: 8 # 17
        trim_tot: 6
      29:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 29
        trim_toa: 29 # 37
        trim_tot: 16
      30:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 18
        trim_toa: 17 # 27
        trim_tot: 6
      31:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 50
        trim_toa: 41 # 49
        trim_tot: 26
      32:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 19
        trim_toa: 60 # 63
        trim_tot: 49
      33:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 30
        trim_toa: 40 # 48
        trim_tot: 16
      34:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 0
        trim_toa: 1 # 6
        trim_tot: 0
      35:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 63
        trim_toa: 43 # 49
        trim_tot: 32
        mask_toa: 1
        mask_tot: 1
      36:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 39
        trim_toa: 42
        trim_tot: 31
      37:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 56
        trim_toa: 44
        trim_tot: 32
      38:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 62
        trim_toa: 54
        trim_tot: 50
      39:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 24
        trim_toa: 27
        trim_tot: 20
      40:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 13
        trim_toa: 23
        trim_tot: 11
      41:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 50
        trim_toa: 35
        trim_tot: 27
      42:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 58
        trim_toa: 47
        trim_tot: 37
      43:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 28
        trim_toa: 25
        trim_tot: 0
      44:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 0
        trim_toa: 32
        trim_tot: 31
        Channel_off: 1
      45:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 33
        trim_toa: 27
        trim_tot: 23
      46:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 20
        trim_toa: 24
        trim_tot: 7
      47:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 5
        trim_toa: 53
        trim_tot: 31
      48:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 58
        trim_toa: 31
        trim_tot: 23
      49:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 36
        trim_toa: 29
        trim_tot: 30
      50:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 35
        trim_toa: 31
        trim_tot: 27
      51:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 63
        trim_toa: 39
        trim_tot: 35
      52:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 0
        trim_toa: 48
        trim_tot: 48
      53:
        Gain_conv: 4
        HZ_noinv: 0
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 29
        trim_toa: 21
        trim_tot: 57
      54:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 34
        trim_toa: 19
        trim_tot: 50
      55:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 24
        trim_toa: 23
        trim_tot: 19
      56:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 50
        trim_toa: 35
        trim_tot: 31
      57:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 20
        trim_toa: 31
        trim_tot: 19
      58:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 38
        trim_toa: 45
        trim_tot: 16
      59:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 35
        trim_toa: 50
        trim_tot: 29
      60:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 47
        trim_toa: 45
        trim_tot: 28
      61:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 30
        trim_toa: 20
        trim_tot: 5
      62:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 50
        trim_toa: 49
        trim_tot: 32
      63:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 47
        trim_toa: 29
        trim_tot: 62
      64:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 61
        trim_toa: 51
        trim_tot: 45
      65:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 36
        trim_toa: 31
        trim_tot: 0
      66:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 5
        trim_toa: 20
        trim_tot: 7
      67:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 13
        trim_toa: 21
        trim_tot: 25
      68:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 48
        trim_toa: 41
        trim_tot: 27
      69:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 52
        trim_toa: 40
        trim_tot: 39
      70:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 42
        trim_toa: 55
        trim_tot: 32
      71:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 0
        trim_toa: 20
        trim_tot: 4
        mask_toa: 1
        mask_tot: 1
       
    cm:
      0:
        Gain_conv: 4
        Inputdac: 31
        dacb: 63
        sign_dac: 0
        trim_inv: 50
        trim_toa: 31
        trim_tot: 31
      1:
        Gain_conv: 4
        Inputdac: 31
        dacb: 63
        sign_dac: 0
        trim_inv: 49
        trim_toa: 31
        trim_tot: 31
      2:
        Gain_conv: 4
        Inputdac: 31
        dacb: 63
        sign_dac: 0
        trim_inv: 55
        trim_toa: 31
        trim_tot: 31
      3:
        Gain_conv: 4
        Inputdac: 31
        dacb: 63
        sign_dac: 0
        trim_inv: 27
        trim_toa: 31
        trim_tot: 31
