daq:
  IdelayStep: '8'
  NChips: '1'
  Number_of_events_per_readout: '-1'
  NEvents: '5000'
  elinks_daq:
    - { name : 'link0', polarity: 1, idcode: 0 } # was 1
    - { name : 'link1', polarity: 1, idcode: 1 } # was 0
  elinks_trg:
    - { name : 'link0', polarity: 0, idcode: 0 } # was 0
    - { name : 'link1', polarity: 1, idcode: 2 } # was 1
    - { name : 'link2', polarity: 1, idcode: 3 } # was 1
    - { name : 'link3', polarity: 0, idcode: 1 } # was 0
  zmqPushPull_port: '8888'
  delayScanData_port: '8889'
  l1a_enables:
    random_l1a         : '0x0'
    external_l1as      : '0x0'
    block_sequencer    : '0x0'
  l1a_generator_settings: # type can be 'L1A', 'L1A_NZS' 'CALPULINT' and 'EXTPULSE0' ; followMode can be DISABLE, A, B, C or D
    - { name : 'A', enable : '0', BX : '0x10', length : '1',   flavor : 'L1A',     prescale : '0x0', followMode : 'DISABLE' }
    - { name : 'B', enable : '0', BX : '0x20', length : '1',   flavor : 'L1A',     prescale : '0x0', followMode : 'DISABLE' }
    - { name : 'C', enable : '0', BX : '0x30', length : '1',   flavor : 'L1A',     prescale : '0x0', followMode : 'DISABLE' }
    - { name : 'D', enable : '0', BX : '0x40', length : '1',   flavor : 'L1A',     prescale : '0x0', followMode : 'DISABLE' }
  l1a_settings:
    bx_spacing: '50'           #Minimum bx spcing between random or external triggers i.e. here : 43 BX between 2 consecutive L1A (when reading 1 BX per event)
    external_debounce: '0xf'   #flags to indicate if external L1A should be debounced (generally a fine idea)
    length: '0x1'              #number of consequitive L1A to send in case of external trigger; don't know yet if it will have any effect on rand L1A gen
    ext_delay: '0x0'           #8-bit delays for each external L1A input
    log2_rand_bx_period: '0x0'  #LOG2(random period) (bigger numbers -> slower trigger rate)

global:
  data_push_port: '8888'
  hw_type: TB
  outputDirectory: data
  run_type: default
  serverIP: tbtester1
  #run_num: 99999
roc_s0:
  sc:
    DigitalHalf:
      0:
        Bx_offset: 2
        CalibrationSC: 1
        L1Offset: 10
      1:
        Bx_offset: 2
        CalibrationSC: 1
        L1Offset: 10
    GlobalAnalog:
      0:
        Cd: 0
        Cf: 10
        Cf_comp: 10
        Dacb_dynran: 0
        Dacb_vb_conv: 6
        Dacb_vbi_pa: 32
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Gain_conv: 0
        Idac_inv: 6
        Idac_tot: 6
        ON_backup: 0
        ON_conv: 1
        Ref_pa_cm: 2
        Rf: 8
        SelExtADC: 0
        SelRisingEdge: 1
      1:
        Cd: 0
        Cf: 10
        Cf_comp: 10
        Dacb_dynran: 0
        Dacb_vb_conv: 6
        Dacb_vbi_pa: 32
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Gain_conv: 0
        Idac_inv: 6
        Idac_tot: 6
        ON_backup: 0
        ON_conv: 1
        Ref_pa_cm: 2
        Rf: 8
        SelExtADC: 0
        SelRisingEdge: 1
    MasterTdc:
      0:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 10
        BIAS_I_FTDC_D: 10
        CTDC_CALIB_FREQUENCY: 2
        EN_MASTER_CTDC_VOUT_INIT: 0
        EN_MASTER_FTDC_VOUT_INIT: 0
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
        START_COUNTER: 1
        VD_CTDC_P_D: 16
        VD_CTDC_P_DAC_EN: 1
        VD_FTDC_P_D: 16
        VD_FTDC_P_DAC_EN: 1
      1:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 10
        BIAS_I_FTDC_D: 10
        CTDC_CALIB_FREQUENCY: 2
        EN_MASTER_CTDC_VOUT_INIT: 0
        EN_MASTER_FTDC_VOUT_INIT: 0
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
        START_COUNTER: 1
        VD_CTDC_P_D: 16
        VD_CTDC_P_DAC_EN: 1
        VD_FTDC_P_D: 16
        VD_FTDC_P_DAC_EN: 1
    ReferenceVoltage:
      0:
        Calib: 0
        Calib_2V5: 0
        IntCtest: 0
        Inv_vref: 550
        Noinv_vref: 850
        Refi: 1
        Toa_vref: 200
        Tot_vref: 678
        Vbg_1v: 3
        choice_cinj: 0
        cmd_120p: 0
      1:
        Calib: 0
        Calib_2V5: 0
        IntCtest: 0
        Inv_vref: 550
        Noinv_vref: 850
        Refi: 1
        Toa_vref: 200
        Tot_vref: 678
        Vbg_1v: 3
        choice_cinj: 0
        cmd_120p: 0
    Top:
      0:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        RunL: 1
        RunR: 1
        phase_ck: 6
    calib:
      0:
        Gain_conv: 3
        Inputdac: 0
        trim_inv: 7
        trim_toa: 31
        trim_tot: 31
      1:
        Gain_conv: 3
        Inputdac: 0
        trim_inv: 21
        trim_toa: 31
        trim_tot: 31
    ch:
      0:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 35
        trim_toa: 63
        trim_tot: 0
      1:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 24
        trim_toa: 63
        trim_tot: 0
      2:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 25
        trim_toa: 63
        trim_tot: 0
      3:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 10
        trim_toa: 63
        trim_tot: 0
      4:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 22
        trim_toa: 63
        trim_tot: 0
      5:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 5
        trim_toa: 63
        trim_tot: 0
      6:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 1
        trim_toa: 63
        trim_tot: 0
      7:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 6
        trim_toa: 63
        trim_tot: 0
      8:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 27
        trim_toa: 63
        trim_tot: 0
      9:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 22
        trim_toa: 63
        trim_tot: 0
      10:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 10
        trim_toa: 63
        trim_tot: 0
      11:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 0
        trim_toa: 63
        trim_tot: 0
      12:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 14
        trim_toa: 63
        trim_tot: 0
      13:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 14
        trim_toa: 63
        trim_tot: 0
      14:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 10
        trim_toa: 63
        trim_tot: 0
      15:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 19
        trim_toa: 63
        trim_tot: 0
      16:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 10
        trim_toa: 63
        trim_tot: 0
      17:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 20
        trim_toa: 63
        trim_tot: 0
      18:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 10
        trim_toa: 63
        trim_tot: 0
      19:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 14
        trim_toa: 63
        trim_tot: 0
      20:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 24
        trim_toa: 63
        trim_tot: 0
      21:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 24
        trim_toa: 63
        trim_tot: 0
      22:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 0
        trim_toa: 63
        trim_tot: 0
      23:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 24
        trim_toa: 63
        trim_tot: 0
      24:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 8
        trim_toa: 63
        trim_tot: 0
      25:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 25
        trim_toa: 63
        trim_tot: 0
      26:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 22
        trim_toa: 63
        trim_tot: 0
      27:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 5
        trim_toa: 63
        trim_tot: 0
      28:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 22
        trim_toa: 63
        trim_tot: 0
      29:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 10
        trim_toa: 63
        trim_tot: 0
      30:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 19
        trim_toa: 63
        trim_tot: 0
      31:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 3
        trim_toa: 63
        trim_tot: 0
      32:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 4
        trim_toa: 63
        trim_tot: 0
      33:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 9
        trim_toa: 63
        trim_tot: 0
      34:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 19
        trim_toa: 63
        trim_tot: 0
      35:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 25
        trim_toa: 63
        trim_tot: 0
      36:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 37
        trim_toa: 63
        trim_tot: 0
      37:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 53
        trim_toa: 63
        trim_tot: 0
      38:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 30
        trim_toa: 63
        trim_tot: 0
      39:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 35
        trim_toa: 63
        trim_tot: 0
      40:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 22
        trim_toa: 63
        trim_tot: 0
      41:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 22
        trim_toa: 63
        trim_tot: 0
      42:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 25
        trim_toa: 63
        trim_tot: 0
      43:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 11
        trim_toa: 63
        trim_tot: 0
      44:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 13
        trim_toa: 63
        trim_tot: 0
      45:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 33
        trim_toa: 63
        trim_tot: 0
      46:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 27
        trim_toa: 63
        trim_tot: 0
      47:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 14
        trim_toa: 63
        trim_tot: 0
      48:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 46
        trim_toa: 63
        trim_tot: 0
      49:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 11
        trim_toa: 63
        trim_tot: 0
      50:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 13
        trim_toa: 63
        trim_tot: 0
      51:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 33
        trim_toa: 63
        trim_tot: 0
      52:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 14
        trim_toa: 63
        trim_tot: 0
      53:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 27
        trim_toa: 63
        trim_tot: 0
      54:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 30
        trim_toa: 63
        trim_tot: 0
      55:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 25
        trim_toa: 63
        trim_tot: 0
      56:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 24
        trim_toa: 63
        trim_tot: 0
      57:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 0
        trim_toa: 63
        trim_tot: 0
      58:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 28
        trim_toa: 63
        trim_tot: 0
      59:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 25
        trim_toa: 63
        trim_tot: 0
      60:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 13
        trim_toa: 63
        trim_tot: 0
      61:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 27
        trim_toa: 63
        trim_tot: 0
      62:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 11
        trim_toa: 63
        trim_tot: 0
      63:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 3
        trim_toa: 63
        trim_tot: 0
      64:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 28
        trim_toa: 63
        trim_tot: 0
      65:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 44
        trim_toa: 63
        trim_tot: 0
      66:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 36
        trim_toa: 63
        trim_tot: 0
      67:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 30
        trim_toa: 63
        trim_tot: 0
      68:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 41
        trim_toa: 63
        trim_tot: 0
      69:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 25
        trim_toa: 63
        trim_tot: 0
      70:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 38
        trim_toa: 63
        trim_tot: 0
      71:
        Gain_conv: 3
        HighRange: 0
        Inputdac: 0
        LowRange: 0
        trim_inv: 38
        trim_toa: 63
        trim_tot: 0
    cm:
      0:
        Gain_conv: 3
        Inputdac: 0
        trim_inv: 63
        trim_toa: 31
        trim_tot: 31
      1:
        Gain_conv: 3
        Inputdac: 0
        trim_inv: 63
        trim_toa: 31
        trim_tot: 31
      2:
        Gain_conv: 3
        Inputdac: 0
        trim_inv: 63
        trim_toa: 31
        trim_tot: 31
      3:
        Gain_conv: 3
        Inputdac: 0
        trim_inv: 63
        trim_toa: 31
        trim_tot: 31
