client:
  data_push_port: '8888'
  hw_type: TB
  outputDirectory: data
  run_type: default
  serverIP: tbtester1
daq:
  IdelayStep: '8'
  NChips: '1'
  Number_of_events_per_readout: '-1'
  active_menu: randomL1A
  delayScanData_port: '8889'
  elinks_daq:
  - idcode: 0
    name: link0
    polarity: 1
  - idcode: 1
    name: link1
    polarity: 1
  elinks_trg:
  - idcode: 0
    name: link0
    polarity: 0
  - idcode: 1
    name: link1
    polarity: 1
  - idcode: 2
    name: link2
    polarity: 1
  - idcode: 3
    name: link3
    polarity: 0
  elinks_trg_phase:
  - idcode: 1
    name: link0
    polarity: 1
  menus:
    calibAndL1A:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
    calibAndL1AplusTPG:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
      trg_fifo_latency: 3
    delayScan:
      acquireLength: 1000
      delayStep: 1
      idlePattern: 0XACCCCCCC
      maxDelay: 512
    dummy:
      NEvents: 10000
      NEventsPerPush: 200
    externalL1A:
      NEvents: 10000
      bxCalibExt: 10
      lengthCalibExt: 2
      loopBack: true
      prescale: 0
      trg_fifo_latency: 3
      trgphase_fifo_latency: 15
    marsRndL1A:
      bx_min: 45
      log2_rand_bx_period: 10
    randomL1A:
      NEvents: 10000
      log2_rand_bx_period: 10
    randomL1AplusTPG:
      NEvents: 10000
      bx_min: 45
      log2_rand_bx_period: 10
      trg_fifo_latency: 3
  zmqPushPull_port: '8888'
metaData:
  Channel_off: []
  characMode: 1
  chip_params: {}
  hexactrl: 10.254.56.35
  hw_type: 1ROC
  keepRawData: 1
  keepSummary: 1
  testName: pedestal_run
roc_s0:
  sc:
    DigitalHalf:
      0:
        Bx_offset: 2
        CalibrationSC: 1
        L1Offset: 10
      1:
        Bx_offset: 2
        CalibrationSC: 1
        L1Offset: 10
    GlobalAnalog:
      0:
        Cd: 0
        Cf: 10
        Cf_comp: 10
        Dacb_dynran: 3
        Dacb_vb_conv: 6
        Dacb_vbi_pa: 32
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Gain_conv: 0
        Idac_inv: 6
        Idac_tot: 6
        ON_backup: 0
        ON_conv: 1
        Ref_pa_cm: 0
        Rf: 12
        SelExtADC: 0
        SelRisingEdge: 1
      1:
        Cd: 0
        Cf: 10
        Cf_comp: 10
        Dacb_dynran: 3
        Dacb_vb_conv: 6
        Dacb_vbi_pa: 32
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Gain_conv: 0
        Idac_inv: 6
        Idac_tot: 6
        ON_backup: 0
        ON_conv: 1
        Ref_pa_cm: 0
        Rf: 12
        SelExtADC: 0
        SelRisingEdge: 1
    MasterTdc:
      0:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 10
        BIAS_I_FTDC_D: 10
        CTDC_CALIB_FREQUENCY: 2
        EN_MASTER_CTDC_VOUT_INIT: 0
        EN_MASTER_FTDC_VOUT_INIT: 0
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
        VD_CTDC_P_D: 16
        VD_CTDC_P_DAC_EN: 1
        VD_FTDC_P_D: 16
        VD_FTDC_P_DAC_EN: 1
      1:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 10
        BIAS_I_FTDC_D: 10
        CTDC_CALIB_FREQUENCY: 2
        EN_MASTER_CTDC_VOUT_INIT: 0
        EN_MASTER_FTDC_VOUT_INIT: 0
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
        VD_CTDC_P_D: 16
        VD_CTDC_P_DAC_EN: 1
        VD_FTDC_P_D: 16
        VD_FTDC_P_DAC_EN: 1
    ReferenceVoltage:
      0:
        Calib_2V5: 0
        Inv_vref: 701
        Noinv_vref: 850
        Refi: 1
        Toa_vref: 900
        Tot_vref: 1000
        Vbg_1v: 3
        choice_cinj: 0
        cmd_120p: 0
      1:
        Calib_2V5: 0
        Inv_vref: 661
        Noinv_vref: 850
        Refi: 1
        Toa_vref: 900
        Tot_vref: 1000
        Vbg_1v: 3
        choice_cinj: 0
        cmd_120p: 0
    Top:
      0:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        RunL: 1
        RunR: 1
    calib:
      0:
        Gain_conv: 4
        Inputdac: 31
        dacb: 12
        sign_dac: 0
        trim_inv: 0
        trim_toa: 31
        trim_tot: 31
      1:
        Gain_conv: 4
        Inputdac: 31
        dacb: 12
        sign_dac: 0
        trim_inv: 0
    ch:
      0:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 61
      1:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 55
      2:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 42
      3:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 41
      4:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 61
      5:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 46
      6:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 39
      7:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 0
      8:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 55
      9:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 61
      10:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 28
      11:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 35
      12:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 50
      13:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 69
      14:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 64
      15:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 48
      16:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 92
      17:
        Gain_conv: 4
        HZ_noinv: 0
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 60
      18:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 70
      19:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 76
      20:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 62
      21:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 27
      22:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 56
      23:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 59
      24:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 55
      25:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 66
      26:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 49
      27:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 39
      28:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 18
      29:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 33
      30:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 30
      31:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 51
      32:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 79
      33:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 40
      34:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 0
      35:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 66
      36:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 27
      37:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 44
      38:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 46
      39:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 21
      40:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 9
      41:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 38
      42:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 40
      43:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 26
      44:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 0
      45:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 24
      46:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 13
      47:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 47
      48:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 44
      49:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 21
      50:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 31
      51:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 47
      52:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 31
      53:
        Gain_conv: 4
        HZ_noinv: 0
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 26
      54:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 29
      55:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 17
      56:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 35
      57:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 12
      58:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 29
      59:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 22
      60:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 31
      61:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 26
      62:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 30
      63:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 37
      64:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 45
      65:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 32
      66:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 3
      67:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 14
      68:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 42
      69:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 40
      70:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 27
      71:
        Gain_conv: 4
        Inputdac: 31
        dacb: 40
        sign_dac: 0
        trim_inv: 0
    cm:
      0:
        Gain_conv: 4
        Inputdac: 31
        dacb: 63
        sign_dac: 0
        trim_inv: 191
      1:
        Gain_conv: 4
        Inputdac: 31
        dacb: 63
        sign_dac: 0
        trim_inv: 165
      2:
        Gain_conv: 4
        Inputdac: 31
        dacb: 63
        sign_dac: 0
        trim_inv: 162
      3:
        Gain_conv: 4
        Inputdac: 31
        dacb: 63
        sign_dac: 0
        trim_inv: 149
