client:
  data_push_port: '8888'
  hw_type: TB
  outputDirectory: data
  run_type: default
  serverIP: tbtester1
daq:
  IdelayStep: '8'
  NChips: '1'
  Number_of_events_per_readout: '-1'
  active_menu: randomL1A
  delayScanData_port: '8889'
  elinks_daq:
  - idcode: 0
    name: link0
    polarity: 1
  - idcode: 1
    name: link1
    polarity: 1
  elinks_trg:
  - idcode: 0
    name: link0
    polarity: 0
  - idcode: 1
    name: link1
    polarity: 1
  - idcode: 2
    name: link2
    polarity: 1
  - idcode: 3
    name: link3
    polarity: 0
  elinks_trg_phase:
  - idcode: 1
    name: link0
    polarity: 1
  menus:
    calibAndL1A:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
    calibAndL1AplusTPG:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
      trg_fifo_latency: 3
    delayScan:
      acquireLength: 1000
      delayStep: 1
      idlePattern: 0XACCCCCCC
      maxDelay: 512
    dummy:
      NEvents: 10000
      NEventsPerPush: 200
    externalL1A:
      NEvents: 10000
      bxCalibExt: 10
      lengthCalibExt: 2
      loopBack: true
      prescale: 0
      trg_fifo_latency: 3
      trgphase_fifo_latency: 15
    marsRndL1A:
      bx_min: 45
      log2_rand_bx_period: 10
    randomL1A:
      NEvents: 10000
      log2_rand_bx_period: 10
    randomL1AplusTPG:
      NEvents: 10000
      bx_min: 45
      log2_rand_bx_period: 10
      trg_fifo_latency: 3
  zmqPushPull_port: '8888'
metaData:
  Channel_off: []
  characMode: 1
  chip_params: {}
  hexactrl: 10.254.56.35
  hw_type: 1ROC
  keepRawData: 1
  keepSummary: 1
  testName: pedestal_run
roc_s0:
  sc:
    DigitalHalf:
      0:
        Bx_offset: 2
        CalibrationSC: 1
        L1Offset: 10
      1:
        Bx_offset: 2
        CalibrationSC: 1
        L1Offset: 10
    GlobalAnalog:
      0:
        Cd: 0
        Cf: 10
        Cf_comp: 10
        Dacb_dynran: 3
        Dacb_vb_conv: 6
        Dacb_vbi_pa: 32
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        En_hyst_tot: 0
        Gain_conv: 0
        Idac_inv: 6
        Idac_tot: 6
        ON_backup: 0
        ON_conv: 1
        Ref_pa_cm: 0
        Rf: 12
        SelExtADC: 0
        SelRisingEdge: 1
      1:
        Cd: 0
        Cf: 10
        Cf_comp: 10
        Dacb_dynran: 3
        Dacb_vb_conv: 6
        Dacb_vbi_pa: 32
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        En_hyst_tot: 0
        Gain_conv: 0
        Idac_inv: 6
        Idac_tot: 6
        ON_backup: 0
        ON_conv: 1
        Ref_pa_cm: 0
        Rf: 12
        SelExtADC: 0
        SelRisingEdge: 1
    MasterTdc:
      0:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 10
        BIAS_I_FTDC_D: 10
        CTDC_CALIB_FREQUENCY: 2
        EN_MASTER_CTDC_VOUT_INIT: 0
        EN_MASTER_FTDC_VOUT_INIT: 0
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
        VD_CTDC_P_D: 16
        VD_CTDC_P_DAC_EN: 1
        VD_FTDC_P_D: 16
        VD_FTDC_P_DAC_EN: 1
      1:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 10
        BIAS_I_FTDC_D: 10
        CTDC_CALIB_FREQUENCY: 2
        EN_MASTER_CTDC_VOUT_INIT: 0
        EN_MASTER_FTDC_VOUT_INIT: 0
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
        VD_CTDC_P_D: 16
        VD_CTDC_P_DAC_EN: 1
        VD_FTDC_P_D: 16
        VD_FTDC_P_DAC_EN: 1
    ReferenceVoltage:
      0:
        Calib_2V5: 0
        Inv_vref: 649
        Noinv_vref: 850
        Refi: 1
        Toa_vref: 198
        Tot_vref: 300
        Vbg_1v: 3
        choice_cinj: 0
        cmd_120p: 0
      1:
        Calib_2V5: 0
        Inv_vref: 678
        Noinv_vref: 850
        Refi: 1
        Toa_vref: 204
        Tot_vref: 300
        Vbg_1v: 3
        choice_cinj: 0
        cmd_120p: 0
    Top:
      0:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        RunL: 1
        RunR: 1
    calib:
      0:
        Gain_conv: 4
        Inputdac: 31
        dacb: 12
        sign_dac: 0
        trim_inv: 0
      1:
        Gain_conv: 4
        Inputdac: 31
        dacb: 12
        sign_dac: 0
        trim_inv: 0
    ch:
      0:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 24
        trim_toa: 17
        trim_tot: 26
      1:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 43
        trim_toa: 28
        trim_tot: 46
      2:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 36
        trim_toa: 16
        trim_tot: 40
      3:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 26
        trim_toa: 31
        trim_tot: 40
      4:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 19
        trim_toa: 0
        trim_tot: 17
      5:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 21
        trim_toa: 8
        trim_tot: 47
      6:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 21
        trim_toa: 8
        trim_tot: 27
      7:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 45
        trim_toa: 20
        trim_tot: 39
      8:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 16
        trim_toa: 8
        trim_tot: 17
      9:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 43
        trim_toa: 18
        trim_tot: 43
      10:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
        trim_toa: 12
        trim_tot: 43
      11:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 29
        trim_toa: 7
        trim_tot: 45
      12:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 44
        trim_toa: 25
        trim_tot: 39
      13:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 50
        trim_toa: 18
        trim_tot: 52
      14:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 11
        trim_toa: 6
        trim_tot: 36
      15:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 33
        trim_toa: 17
        trim_tot: 35
      16:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 35
        trim_toa: 20
        trim_tot: 44
      17:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 36
        trim_toa: 16
        trim_tot: 41
      18:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 17
        trim_toa: 7
        trim_tot: 35
      19:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 41
        trim_toa: 20
        trim_tot: 42
      20:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 20
        trim_toa: 14
        trim_tot: 29
      21:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 34
        trim_toa: 12
        trim_tot: 39
      22:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 36
        trim_toa: 15
        trim_tot: 37
      23:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 35
        trim_toa: 21
        trim_tot: 40
      24:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 42
        trim_toa: 9
        trim_tot: 41
      25:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 41
        trim_toa: 19
        trim_tot: 36
      26:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 18
        trim_toa: 17
        trim_tot: 28
      27:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 25
        trim_toa: 8
        trim_tot: 35
      28:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 42
        trim_toa: 28
        trim_tot: 34
      29:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 30
        trim_toa: 11
        trim_tot: 30
      30:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
        trim_toa: 9
        trim_tot: 29
      31:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 24
        trim_toa: 8
        trim_tot: 26
      32:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 15
        trim_toa: 4
        trim_tot: 29
      33:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 27
        trim_toa: 24
        trim_tot: 45
      34:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 58
        trim_toa: 32
        trim_tot: 38
      35:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 32
        trim_toa: 20
        trim_tot: 40
      36:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 55
        trim_toa: 27
        trim_tot: 37
      37:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 9
        trim_toa: 12
        trim_tot: 26
      38:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 41
        trim_toa: 14
        trim_tot: 22
      39:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 39
        trim_toa: 7
        trim_tot: 28
      40:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 37
        trim_toa: 17
        trim_tot: 43
      41:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 26
        trim_toa: 11
        trim_tot: 20
      42:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 18
        trim_toa: 15
        trim_tot: 31
      43:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 24
        trim_toa: 7
        trim_tot: 19
      44:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 30
        trim_toa: 4
        trim_tot: 26
      45:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 0
        trim_toa: 0
        trim_tot: 22
      46:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 46
        trim_toa: 14
        trim_tot: 33
      47:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 14
        trim_toa: 7
        trim_tot: 20
      48:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 26
        trim_toa: 8
        trim_tot: 35
      49:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 25
        trim_toa: 2
        trim_tot: 22
      50:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 44
        trim_toa: 15
        trim_tot: 29
      51:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 9
        trim_toa: 0
        trim_tot: 7
      52:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 35
        trim_toa: 4
        trim_tot: 29
      53:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 43
        trim_toa: 18
        trim_tot: 46
      54:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 32
        trim_toa: 8
        trim_tot: 37
      55:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 12
        trim_toa: 10
        trim_tot: 24
      56:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 43
        trim_toa: 23
        trim_tot: 19
      57:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 28
        trim_toa: 6
        trim_tot: 23
      58:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 35
        trim_toa: 3
        trim_tot: 32
      59:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 17
        trim_toa: 9
        trim_tot: 21
      60:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 34
        trim_toa: 12
        trim_tot: 24
      61:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 32
        trim_toa: 20
        trim_tot: 22
      62:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 19
        trim_toa: 2
        trim_tot: 8
      63:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 33
        trim_toa: 3
        trim_tot: 24
      64:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 48
        trim_toa: 16
        trim_tot: 29
      65:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 23
        trim_toa: 11
        trim_tot: 19
      66:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 13
        trim_toa: 7
        trim_tot: 21
      67:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 42
        trim_toa: 17
        trim_tot: 28
      68:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 32
        trim_toa: 19
        trim_tot: 32
      69:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 38
        trim_toa: 10
        trim_tot: 42
      70:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 27
        trim_toa: 4
        trim_tot: 34
      71:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 27
        trim_toa: 0
        trim_tot: 23
    cm:
      0:
        Gain_conv: 4
        Inputdac: 0
        dacb: 0
        sign_dac: 0
        trim_inv: 0
      1:
        Gain_conv: 4
        Inputdac: 0
        dacb: 0
        sign_dac: 0
        trim_inv: 0
      2:
        Gain_conv: 4
        Inputdac: 0
        dacb: 0
        sign_dac: 0
        trim_inv: 0
      3:
        Gain_conv: 4
        Inputdac: 0
        dacb: 0
        sign_dac: 0
        trim_inv: 0
