trg_lpgbt:
  CHIPCONFIG: 0
  CLKGCDRFFPROPCUR: 102
  CLKGCDRINTCUR: 85
  CLKGCDRPROPCUR: 85
  CLKGCNTOVERRIDE: 0
  CLKGCONFIG0: 232
  CLKGCONFIG1: 56
  CLKGFFCAP: 27
  CLKGFLLINTCUR: 85
  CLKGLFCONFIG0: 143
  CLKGLFCONFIG1: 255
  CLKGOVERRIDECAPBANK: 0
  CLKGPLLINTCUR: 153
  CLKGPLLPROPCUR: 153
  CLKGPLLRES: 34
  CLKGWAITTIME: 136
  DPDATAPATTERN0: 204
  DPDATAPATTERN1: 204
  DPDATAPATTERN2: 204
  DPDATAPATTERN3: 204
  EPRXECCHNCNTR: 2
  EPRXECCONTROL: 16
  EPTXECCHNCNTR: 227
  EQCONFIG: 24
  EQRES: 0
  LDCONFIGH: 96
  POWERUP2: 0
  PSDLLCONFIG: 0
  ULDATASOURCE0: 0
  ULDATASOURCE1: 36
  ULDATASOURCE2: 36
  ULDATASOURCE3: 36
  ULDATASOURCE4: 4
