daq_lpgbt:
  EPTX00CHNCNTR: 7
  EPTX01CHNCNTR: 7
  EPTX01_00CHNCNTR: 136
  EPTX02CHNCNTR: 7
  EPTX03CHNCNTR: 7
  EPTX03_02CHNCNTR: 136
  EPTX10CHNCNTR: 7
  EPTX10ENABLE: 7
  EPTX11CHNCNTR: 7
  EPTX11_10CHNCNTR: 136
  EPTX12CHNCNTR: 7
  EPTX13CHNCNTR: 7
  EPTX13_12CHNCNTR: 0
  EPTX20CHNCNTR: 7
  EPTX21CHNCNTR: 7
  EPTX21_20CHNCNTR: 0
  EPTX22CHNCNTR: 7
  EPTX23CHNCNTR: 7
  EPTX23_22CHNCNTR: 136
  EPTX30CHNCNTR: 7
  EPTX31CHNCNTR: 7
  EPTX31_30CHNCNTR: 136
  EPTX32CHNCNTR: 7
  EPTX32ENABLE: 43
  EPTX33CHNCNTR: 7
  EPTX33_32CHNCNTR: 136
  EPTXCONTROL: 13
  EPTXDATARATE: 243
