daq_lpgbt:
  EPCLK19CHNCNTRH: 44
  EPCLK19CHNCNTRL: 0
  EPCLK1CHNCNTRH: 25
  EPCLK1CHNCNTRL: 0
  EPCLK21CHNCNTRH: 44
  EPCLK21CHNCNTRL: 0
  EPCLK22CHNCNTRH: 44
  EPCLK22CHNCNTRL: 0
  EPCLK23CHNCNTRH: 44
  EPCLK23CHNCNTRL: 0
  EPCLK27CHNCNTRH: 25
  EPCLK27CHNCNTRL: 0
  EPCLK28CHNCNTRH: 44
  EPCLK28CHNCNTRL: 0
  EPCLK4CHNCNTRH: 44
  EPCLK4CHNCNTRL: 0
  EPCLK6CHNCNTRH: 44
  EPCLK6CHNCNTRL: 0
