trg_lpgbt:
  EPRX00CHNCNTR: 7
  EPRX01CHNCNTR: 7
  EPRX02CHNCNTR: 7
  EPRX03CHNCNTR: 7
  EPRX0CONTROL: 30
  EPRX10CHNCNTR: 2
  EPRX11CHNCNTR: 2
  EPRX12CHNCNTR: 2
  EPRX13CHNCNTR: 2
  EPRX1CONTROL: 30
  EPRX20CHNCNTR: 10
  EPRX21CHNCNTR: 10
  EPRX22CHNCNTR: 10
  EPRX23CHNCNTR: 10
  EPRX2CONTROL: 30
  EPRX30CHNCNTR: 10
  EPRX31CHNCNTR: 10
  EPRX32CHNCNTR: 10
  EPRX33CHNCNTR: 10
  EPRX3CONTROL: 30
  EPRX40CHNCNTR: 2
  EPRX41CHNCNTR: 2
  EPRX42CHNCNTR: 2
  EPRX43CHNCNTR: 2
  EPRX4CONTROL: 30
  EPRX50CHNCNTR: 2
  EPRX51CHNCNTR: 2
  EPRX52CHNCNTR: 2
  EPRX53CHNCNTR: 2
  EPRX5CONTROL: 30
  EPRX60CHNCNTR: 10
  EPRX61CHNCNTR: 10
  EPRX62CHNCNTR: 10
  EPRX63CHNCNTR: 10
  EPRX6CONTROL: 30
