daq_lpgbt:
  CHIPCONFIG: 0
  CLKGCDRFFPROPCUR: 102
  CLKGCDRINTCUR: 85
  CLKGCDRPROPCUR: 85
  CLKGCNTOVERRIDE: 0
  CLKGCONFIG0: 232
  CLKGCONFIG1: 56
  CLKGFFCAP: 27
  CLKGFLLINTCUR: 85
  CLKGLFCONFIG0: 143
  CLKGLFCONFIG1: 255
  CLKGOVERRIDECAPBANK: 0
  CLKGPLLINTCUR: 153
  CLKGPLLPROPCUR: 153
  CLKGPLLRES: 34
  CLKGWAITTIME: 136
  DPDATAPATTERN0: 170
  DPDATAPATTERN1: 170
  DPDATAPATTERN2: 170
  DPDATAPATTERN3: 170
  EPRXECCHNCNTR: 1
  EPRXECCONTROL: 16
  EPTXECCHNCNTR: 225
  EQCONFIG: 24
  EQRES: 0
  FAMAXHEADERFOUNDCOUNT: 16
  FAMAXHEADERFOUNDCOUNTAFTERNF: 16
  FAMAXHEADERNOTFOUNDCOUNT: 16
  LDCONFIGH: 96
  LDCONFIGL: 0
  POWERUP0: 0
  POWERUP1: 0
  POWERUP2: 0
  PSDLLCONFIG: 0
  ULDATASOURCE0: 0
  ULDATASOURCE1: 36
  ULDATASOURCE2: 36
  ULDATASOURCE3: 36
  ULDATASOURCE4: 4
