daq_lpgbt:
  EPRX00CHNCNTR: 2
  EPRX01CHNCNTR: 2
  EPRX02CHNCNTR: 2
  EPRX03CHNCNTR: 2
  EPRX0CONTROL: 30
  EPRX10CHNCNTR: 2
  EPRX11CHNCNTR: 2
  EPRX12CHNCNTR: 2
  EPRX13CHNCNTR: 2
  EPRX1CONTROL: 30
  EPRX20CHNCNTR: 2
  EPRX21CHNCNTR: 2
  EPRX22CHNCNTR: 2
  EPRX23CHNCNTR: 2
  EPRX2CONTROL: 30
  EPRX30CHNCNTR: 2
  EPRX31CHNCNTR: 2
  EPRX32CHNCNTR: 2
  EPRX33CHNCNTR: 2
  EPRX3CONTROL: 30
  EPRX40CHNCNTR: 2
  EPRX41CHNCNTR: 2
  EPRX42CHNCNTR: 2
  EPRX43CHNCNTR: 2
  EPRX4CONTROL: 30
  EPRX50CHNCNTR: 2
  EPRX51CHNCNTR: 2
  EPRX52CHNCNTR: 2
  EPRX53CHNCNTR: 2
  EPRX5CONTROL: 30
  EPRX60CHNCNTR: 2
  EPRX61CHNCNTR: 2
  EPRX62CHNCNTR: 2
  EPRX63CHNCNTR: 2
  EPRX6CONTROL: 30
