daq:
  IdelayStep: '8'
  NChips: '1'
  Number_of_events_per_readout: '-1'
  active_menu : 'randomL1A'
  
  elinks_daq:
    - { name : 'link0', polarity: 1, idcode: 0 }
    - { name : 'link1', polarity: 1, idcode: 1 }

  elinks_trg:
    - { name : 'link0', polarity: 0, idcode: 0 }
    - { name : 'link1', polarity: 1, idcode: 1 }
    - { name : 'link2', polarity: 1, idcode: 2 }
    - { name : 'link3', polarity: 0, idcode: 3 }


  elinks_trg_phase: ##only needed when using external L1A source 
    - { name : 'link0', polarity: 1, idcode: 1 }
 

  zmqPushPull_port: '8888'
  delayScanData_port: '8889'
  menus:
    dummy:
      NEvents: 10000
      NEventsPerPush: 200
    #randomL1a:
    randomL1A:
      NEvents: 10000
      log2_rand_bx_period: 10
    randomL1AplusTPG:
      NEvents: 10000
      log2_rand_bx_period: 10
      bx_min: 45
      trg_fifo_latency: 3
    externalL1A:
      NEvents: 10000
      trg_fifo_latency: 3
      trgphase_fifo_latency: 15
      loopBack: true
      bxCalibExt: 10
      lengthCalibExt: 2
      prescale: 0
    calibAndL1A:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
    calibAndL1AplusTPG:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
      trg_fifo_latency: 3
    delayScan:
      maxDelay: 512
      delayStep: 1
      idlePattern: '0XACCCCCCC'
      acquireLength: 1000
    marsRndL1A:
      log2_rand_bx_period: 10
      bx_min: 45
client:
  data_push_port: '8888'
  hw_type: TB
  outputDirectory: data
  run_type: default
  serverIP: tbtester1
  #run_num: 99999
roc_s0:
  sc:
    DigitalHalf:
      0:
        L1Offset: 11
        Bx_offset: 2
        CalibrationSC: 1
      1: 
        L1Offset: 11
        Bx_offset: 2
        CalibrationSC: 1
    GlobalAnalog:
      0:
        Delay9: 3
        Delay87: 3
        Delay65: 3
        Delay40: 2
        Idac_inv: 6
        Idac_tot: 6
        Ref_pa_cm: 0
        ON_backup: 0
        ON_conv: 1
        SelExtADC: 0
        SelRisingEdge: 1
        Dacb_dynran: 3
        Gain_conv: 1
        Cd: 0
        Cf_comp: 10
        Cf: 10
        Rf: 12
        Dacb_vbi_pa: 32
        Dacb_vb_conv: 6
      1:
        Delay9: 3
        Delay87: 3
        Delay65: 3
        Delay40: 2
        Idac_inv: 6
        Idac_tot: 6
        Ref_pa_cm: 0
        ON_backup: 0
        ON_conv: 1
        SelExtADC: 0
        SelRisingEdge: 1
        Dacb_dynran: 3
        Gain_conv: 1
        Cd: 0
        Cf_comp: 10
        Cf: 10
        Rf: 12
        Dacb_vbi_pa: 32
        Dacb_vb_conv: 6
    ReferenceVoltage:
      0:
        Vbg_1v: 3
        Refi: 1
        choice_cinj: 0
        cmd_120p: 0
        Calib_2V5: 0
        Inv_vref: 550
        Noinv_vref: 850
        Tot_vref: 600
        Toa_vref: 550
      1:
        Vbg_1v: 3
        Refi: 1
        choice_cinj: 0
        cmd_120p: 0
        Calib_2V5: 0
        Inv_vref: 550
        Noinv_vref: 850
        Tot_vref: 600
        Toa_vref: 550
    MasterTdc:
      0:
        BIAS_I_CTDC_D: 10
        FOLLOWER_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4
        GLOBAL_EN_BUFFER_CTDC: 1
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_I_FTDC_D: 10
        FOLLOWER_FTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        GLOBAL_EN_BUFFER_FTDC: 1
        CTDC_CALIB_FREQUENCY: 2
        FTDC_CALIB_FREQUENCY: 2
      1:
        BIAS_I_CTDC_D: 10
        FOLLOWER_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4
        GLOBAL_EN_BUFFER_CTDC: 1
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_I_FTDC_D: 10
        FOLLOWER_FTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        GLOBAL_EN_BUFFER_FTDC: 1
        CTDC_CALIB_FREQUENCY: 2
        FTDC_CALIB_FREQUENCY: 2
    Top:
      0:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        RunL: 1
        RunR: 1
        EN_probe_pll: 1
        DIV_PLL: 0
      1:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        RunL: 1
        RunR: 1
        EN_probe_pll: 1
        DIV_PLL: 0

roc_s1:
