daq:
  IdelayStep: '8'
  NChips: '2'
  Number_of_events_per_readout: '-1'
  active_menu : 'randomL1A'
  
  elinks_daq:
    - { name : 'link0', polarity: 1, idcode: 0 }
    - { name : 'link1', polarity: 1, idcode: 1 }
    - { name : 'link2', polarity: 1, idcode: 36 }
  elinks_trg:
    - { name : 'link0', polarity: 0, idcode: 0 }
    - { name : 'link1', polarity: 1, idcode: 2 }
    - { name : 'link2', polarity: 1, idcode: 3 }
    - { name : 'link3', polarity: 0, idcode: 1 }
    - { name : 'link4', polarity: 1, idcode: 36 }
    - { name : 'link5', polarity: 1, idcode: 37 }

  elinks_trg_phase: ##only needed when using external L1A source 
    - { name : 'link0', polarity: 1, idcode: 1 }
 

  zmqPushPull_port: '8888'
  delayScanData_port: '8889'
  menus:
    dummy:
      NEvents: 10000
      NEventsPerPush: 200
    #randomL1a:
    randomL1A:
      NEvents: 10000
      log2_rand_bx_period: 10
    randomL1AplusTPG:
      NEvents: 10000
      log2_rand_bx_period: 10
      bx_min: 45
      trg_fifo_latency: 3
    externalL1A:
      NEvents: 10000
      trg_fifo_latency: 3
      trgphase_fifo_latency: 15
      loopBack: true
      bxCalibExt: 10
      lengthCalibExt: 2
      prescale: 0
    calibAndL1A:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
    calibAndL1AplusTPG:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
      trg_fifo_latency: 3
    delayScan:
      maxDelay: 512
      delayStep: 1
      idlePattern: '0XACCCCCCC'
      acquireLength: 1000
    marsRndL1A:
      log2_rand_bx_period: 10
      bx_min: 45
client:
  data_push_port: '8888'
  hw_type: TB
  outputDirectory: data
  run_type: default
  serverIP: tbtester1
  #run_num: 99999
roc_s0:
  sc:
    DigitalHalf:
      0:
        L1Offset: 10
roc_s1:
  sc:
    DigitalHalf:
      0:
        L1Offset: 10
